# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    app.mailer.transport:  I`m sent to constructor
services:
    app.mailer:
        class:        AppBundle\Mailer
        arguments:    ['%app.mailer.transport%']
    app.tweeter:
        class:        AppBundle\TweetSender
        arguments:    ['@app.mailer']